FROM node:18-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache python3 make g++ git

# Copy package files
COPY ./apps/cms/package*.json ./

# Install dependencies
RUN yarn install

# Create the strapi app directory and set permissions
RUN mkdir -p /app/node_modules
RUN chown -R node:node /app

# Switch to non-root user
USER node

# Copy the existing Strapi project
COPY --chown=node:node ./apps/cms .

# Expose port
EXPOSE 1337

# Start development server
CMD ["yarn", "develop"]
